services:
  api:
    build: .
    container_name: feedbackpilot_api
    command: >
      uv run uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app         # only API gets the live code mount

  worker:
    build: .
    container_name: feedbackpilot_worker
    command: >
      uv run celery
      -A app.celery_app.celery_app
      worker
      --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - db
      - redis
    # NO volumes here

  beat:
    build: .
    container_name: feedbackpilot_beat
    command: >
      uv run celery
      -A app.celery_app.celery_app
      beat
      --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis
    # NO volumes here

  db:
    image: postgres:16
    container_name: feedbackpilot_db
    env_file:
      - .env
    ports:
      - "5433:5432"   # or "5433:5432" if 5432 on host is already in use
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: feedbackpilot_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
