services:
  api:
    build: .
    container_name: productboard_api
    command: >
      uv run uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload
    env_file:
      - .env
    depends_on:
      # - db        # maybe, see Supabase section below
      - redis
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  worker:
    build: .
    container_name: productboard_worker
    command: >
      uv run celery
      -A celery_app.celery_app
      worker
      --loglevel=INFO
    env_file:
      - .env
    depends_on:
      # - db        # remove if you drop local Postgres
      - redis

  beat:
    build: .
    container_name: productboard_beat
    command: >
      uv run celery
      -A celery_app.celery_app
      beat
      --loglevel=INFO
    env_file:
      - .env
    depends_on:
      - redis

  # db:
  #   image: postgres:16
  #   container_name: productboard_db
  #   env_file:
  #     - .env
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: productboard_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
